# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fluid Mechanics Class Notes
author: Carlos D. Hoyos 
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  packages:
    - amsmath
    - amssymb
    - tikz

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/carlosdhoyos/fluid_mechanics  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true  # Adds a button to link to the GitHub issues page
  use_repository_button: true  # Adds a button to link to the repository
  theme:
    name: sphinx_book_theme
    options:
      default_mode: "light"  # Ensures the light theme is the default
      navbar_align: content  # Aligns the navigation bar with the content
      launch_buttons: false  # Disables extra buttons that can crowd the UI
      home_page_in_toc: true  # Ensures the home page is in the table of contents
      show_navbar_depth: 2  # Controls the depth of the navbar, reducing clutter
      show_toc_level: 2  # Controls how many levels of headers are shown in the sidebar
      numbering: true  # Enable automatic numbering for chapters and sections

launch_buttons:
  thebe: false  # This enables Thebe for interactive code cells
